[package]
name = "toile-cli"
version = "0.1.0"
authors = ["Sam Wilson <sam.wilson@consensys.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
